### ISSUE TITLE
improv: java 9

### ISSUE THREAD

**Issue by Eywek** [MineWeb/ServerBridge#1]
we need to stop use this https://github.com/MineWeb/ServerBridge/blob/master/src/main/java/fr/vmarchaud/mineweb/utils/CryptoUtils.java#L8

**Comment by Shyrogan** [comment]
Removed in Java 11 and throw a `java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter`

**Comment by Shyrogan** [comment]
#8 library is shaded with the plugin

**Comment by Shyrogan** [comment]
@Eywek vrai homme ferme les issues réglées 🤔

**Comment by MaximeMichaud** [comment]
Yep, j'allais en avertir Eywek, mais ma connexion n'aide pas.
Précision : Testée et fonctionne avec la 3.0.0 avec Java 11.
