### ISSUE TITLE
Erreur avec le plugin LibDisguise

### ISSUE THREAD

**Issue by skyfyx** [MineWeb/ServerBridge#5]
Bonjour , 

En installant le plugin pour relier la boutique du site au server ( MineBridge 2.0) j'ai le plugins Libdisguise qui a une erreur et si j'enlève Minebridge je n'ai plus d'erreur.
Comment puis je faire pour lier le site au serveur ? 

Merci d'avance

**Comment by sadoj-kuro** [comment]
Rcon

**Comment by Romuux** [comment]
Téléchargez la version : https://github.com/MineWeb/ServerBridge/raw/no-injector/mineweb_bridge-2.0.0.jar

Le problème vient du faite que la version que vous utilisez du bridge entre en conflit avec protocollib et empêche donc tout les plugins qui utilisent protocollib de démarrer correctement.
La version donnée plus haut est un version dites "no injector" qui évite le soucis. 

Voir https://github.com/MineWeb/docs.mineweb.org/blob/master/source/includes/_link_server.md pour plus d'information ou Kuro sur Discord qui vient de me donner la solution ;)
